export const ADD_EMPLOYEE_START = " ADD_EMPLOYEE_START ";
export const ADD_EMPLOYEE_SUCCESS = " ADD_EMPLOYEE_SUCCESS ";
export const ADD_EMPLOYEE_FAIL = " ADD_EMPLOYEE_FAIL ";

export const DELETE_EMPLOYEE_START = " DELETE_EMPLOYEE_START ";
export const DELETE_EMPLOYEE_SUCCESS = " DELETE_EMPLOYEE_SUCCESS ";
export const DELETE_EMPLOYEE_FAIL = " DELETE_EMPLOYEE_FAIL ";

export const UPDATE_EMPLOYEE_START = " UPDATE_EMPLOYEE_START ";
export const UPDATE_EMPLOYEE_SUCCESS = " UPDATE_EMPLOYEE_SUCCESS ";
export const UPDATE_EMPLOYEE_FAIL = " UPDATE_EMPLOYEE_FAIL ";

export const EMPLOYEE_LIST_START =" EMPLOYEE_LIST_START ";
export const EMPLOYEE_LIST_SUCCESS =" EMPLOYEE_LIST_SUCCESS ";
export const EMPLOYEE_LIST_FAIL =" EMPLOYEE_LIST_FAIL ";


